In [19]:
import numpy as np
import matplotlib.pyplot as plt

import pywt
import pywt.data

from PIL import Image

ourOriginal = Image.open("/home/abishai/Pictures/LA_projectImg.jpg")
ourOriginalArray = np.array(ourOriginal)

In [20]:
print(ourOriginalArray)

[[[101 104 109]
  [ 99 102 107]
  [ 98 101 106]
  ...
  [122 124 123]
  [122 124 123]
  [122 124 123]]

 [[101 104 109]
  [100 103 108]
  [ 99 102 107]
  ...
  [122 124 123]
  [122 124 123]
  [123 125 124]]

 [[101 104 109]
  [100 103 108]
  [ 99 102 107]
  ...
  [122 124 123]
  [122 124 123]
  [123 125 124]]

 ...

 [[ 97  72  50]
  [ 98  73  51]
  [ 99  74  52]
  ...
  [  6   6   6]
  [  6   6   6]
  [  7   7   7]]

 [[100  76  52]
  [100  76  52]
  [102  78  54]
  ...
  [  7   5   6]
  [  7   7   7]
  [  8   8   8]]

 [[101  77  53]
  [102  78  54]
  [103  79  55]
  ...
  [  7   5   6]
  [  7   7   7]
  [  9   9   9]]]


In [23]:
cA,cD = pywt.dwt(ourOriginalArray,'haar')

In [26]:
cA

array([[[144.95689014, 154.1492783 ],
        [142.12846302, 151.32085117],
        [140.71424946, 149.90663761],
        ...,
        [173.94826817, 173.94826817],
        [173.94826817, 173.94826817],
        [173.94826817, 173.94826817]],

       [[144.95689014, 154.1492783 ],
        [143.54267658, 152.73506474],
        [142.12846302, 151.32085117],
        ...,
        [173.94826817, 173.94826817],
        [173.94826817, 173.94826817],
        [175.36248173, 175.36248173]],

       [[144.95689014, 154.1492783 ],
        [143.54267658, 152.73506474],
        [142.12846302, 151.32085117],
        ...,
        [173.94826817, 173.94826817],
        [173.94826817, 173.94826817],
        [175.36248173, 175.36248173]],

       ...,

       [[119.50104602,  70.71067812],
        [120.91525958,  72.12489168],
        [122.32947315,  73.53910524],
        ...,
        [  8.48528137,   8.48528137],
        [  8.48528137,   8.48528137],
        [  9.89949494,   9.89949494]],

       [[124.45

In [27]:
cD

array([[[-2.12132034,  0.        ],
        [-2.12132034,  0.        ],
        [-2.12132034,  0.        ],
        ...,
        [-1.41421356,  0.        ],
        [-1.41421356,  0.        ],
        [-1.41421356,  0.        ]],

       [[-2.12132034,  0.        ],
        [-2.12132034,  0.        ],
        [-2.12132034,  0.        ],
        ...,
        [-1.41421356,  0.        ],
        [-1.41421356,  0.        ],
        [-1.41421356,  0.        ]],

       [[-2.12132034,  0.        ],
        [-2.12132034,  0.        ],
        [-2.12132034,  0.        ],
        ...,
        [-1.41421356,  0.        ],
        [-1.41421356,  0.        ],
        [-1.41421356,  0.        ]],

       ...,

       [[17.67766953,  0.        ],
        [17.67766953,  0.        ],
        [17.67766953,  0.        ],
        ...,
        [ 0.        ,  0.        ],
        [ 0.        ,  0.        ],
        [ 0.        ,  0.        ]],

       [[16.97056275,  0.        ],
        [16.97056275,  0.  

In [33]:
img = Image.fromarray(cA, 'RGB')
img.save('test.png')
img.show()

In [34]:
img = Image.fromarray(cD, 'RGB')
img.save('test2.png')
img.show()